CREATE TABLE agreements (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  type VARCHAR(40) NOT NULL,
  agreed BOOLEAN NOT NULL,
  agreed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  ip VARCHAR(40),
  ua VARCHAR(255),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);
