services:
  mysql-main:
    image: mysql:8
    container_name: mysql-main
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: leisure_db
      MYSQL_USER: leisure_user
      MYSQL_PASSWORD: 1234
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./mysql-data:/var/lib/mysql

  redis-main:
    image: redis:7
    container_name: redis-main
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./initdb:/docker-entrypoint-initdb.d
