spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leisure_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: leisure_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
